[tool.poetry]
name = "api-mngr"
version = "0.1.0"
description = ""
authors = ["Touko Peltomaa <touko.peltomaa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
